plugins {
    id 'com.android.application'
}

android {
    namespace = 'lab.prada.android.ui.mymodule.app'
    compileSdk 37

    defaultConfig {
        applicationId 'lab.prada.android.ui.mymodule.app'
        minSdk 21
        targetSdk 37
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':library')
}
